=begin
#barcodeapi

#Barcode APIs let you generate barcode images, and recognize values from images of barcodes.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveBarcodeApiClient::BarcodeLookupResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BarcodeLookupResponse' do
  before do
    # run before each test
    @instance = CloudmersiveBarcodeApiClient::BarcodeLookupResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BarcodeLookupResponse' do
    it 'should create an instance of BarcodeLookupResponse' do
      expect(@instance).to be_instance_of(CloudmersiveBarcodeApiClient::BarcodeLookupResponse)
    end
  end
  describe 'test attribute "successful"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "matches"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

