=begin
#barcodeapi

#Barcode APIs let you generate barcode images, and recognize values from images of barcodes.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveBarcodeApiClient::BarcodeScanApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BarcodeScanApi' do
  before do
    # run before each test
    @instance = CloudmersiveBarcodeApiClient::BarcodeScanApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BarcodeScanApi' do
    it 'should create an instance of BarcodeScanApi' do
      expect(@instance).to be_instance_of(CloudmersiveBarcodeApiClient::BarcodeScanApi)
    end
  end

  # unit tests for barcode_scan_image
  # Scan an image for a barcode and turn the result.  Supported barcode types include AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB
  # 
  # @param image_file Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
  # @param [Hash] opts the optional parameters
  # @return [BarcodeScanResult]
  describe 'barcode_scan_image test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
