=begin
#barcodeapi

#Barcode APIs let you generate barcode images, and recognize values from images of barcodes.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveBarcodeApiClient::GenerateBarcodeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GenerateBarcodeApi' do
  before do
    # run before each test
    @instance = CloudmersiveBarcodeApiClient::GenerateBarcodeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GenerateBarcodeApi' do
    it 'should create an instance of GenerateBarcodeApi' do
      expect(@instance).to be_instance_of(CloudmersiveBarcodeApiClient::GenerateBarcodeApi)
    end
  end

  # unit tests for generate_barcode_code128
  # Generate a EAN-13 code barcode as PNG file
  # Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
  # @param value Barcode value to generate from
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :width Optional: width of the barcode in pixels.  Minimum value of 10.
  # @option opts [Integer] :height Optional: width of the barcode in pixels.  Minimum value of 10.
  # @option opts [BOOLEAN] :include_label Optional: show text label on the image of the barcode value, default is true.
  # @return [String]
  describe 'generate_barcode_code128 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for generate_barcode_ean13
  # Generate a EAN-13 code barcode as PNG file
  # Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
  # @param value Barcode value to generate from
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :width Optional: width of the barcode in pixels.  Minimum value of 10.
  # @option opts [Integer] :height Optional: width of the barcode in pixels.  Minimum value of 10.
  # @option opts [BOOLEAN] :include_label Optional: show text label on the image of the barcode value, default is true.
  # @return [String]
  describe 'generate_barcode_ean13 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for generate_barcode_ean8
  # Generate a EAN-8 code barcode as PNG file
  # Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode
  # @param value Barcode value to generate from
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :width Optional: width of the barcode in pixels.  Minimum value of 10.
  # @option opts [Integer] :height Optional: width of the barcode in pixels.  Minimum value of 10.
  # @option opts [BOOLEAN] :include_label Optional: show text label on the image of the barcode value, default is true.
  # @return [String]
  describe 'generate_barcode_ean8 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for generate_barcode_qr_code
  # Generate a QR code barcode as PNG file
  # Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information
  # @param value QR code text to convert into the QR code barcode
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :width Optional: width of the barcode in pixels.  Minimum value of 10.
  # @option opts [Integer] :height Optional: width of the barcode in pixels.  Minimum value of 10.
  # @return [String]
  describe 'generate_barcode_qr_code test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for generate_barcode_upca
  # Generate a UPC-A code barcode as PNG file
  # Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode
  # @param value UPC-A barcode value to generate from
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :width Optional: width of the barcode in pixels.  Minimum value of 10.
  # @option opts [Integer] :height Optional: width of the barcode in pixels.  Minimum value of 10.
  # @option opts [BOOLEAN] :include_label Optional: show text label on the image of the barcode value, default is true.
  # @return [String]
  describe 'generate_barcode_upca test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for generate_barcode_upce
  # Generate a UPC-E code barcode as PNG file
  # Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode
  # @param value UPC-E barcode value to generate from
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :width Optional: width of the barcode in pixels.  Minimum value of 10.
  # @option opts [Integer] :height Optional: width of the barcode in pixels.  Minimum value of 10.
  # @option opts [BOOLEAN] :include_label Optional: show text label on the image of the barcode value, default is true.
  # @return [String]
  describe 'generate_barcode_upce test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
